<? php
echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"';
echo '"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">';
echo '<html xmlns="http://www.w3.org/1999/xhtml">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<head>';
echo '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-114673456-1"></script>';
echo '<script>';
echo 'window.dataLayer = window.dataLayer || [];';
echo 'function gtag(){dataLayer.push(arguments);}';
echo 'gtag('js', new Date());';
echo '';
echo 'gtag('config', 'UA-114673456-1');';
echo '</script>';
echo '';
echo '';
echo '<link rel="stylesheet"';
echo 'href="stylesheet.css"';
echo 'type="text/css"  />';
echo '<title>ノーノム</title>';
echo '</head>';
echo '<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">';
echo '<body>';
echo '<pre> _ __   ___  _ __ ___  _ __   ___  _ __ ___';
echo '| '_ \ / _ \| '_ ` _ \| '_ \ / _ \| '_ ` _ \';
echo '| | | | (_) | | | | | | | | | (_) | | | | | |';
echo '|_| |_|\___/|_| |_| |_|_| |_|\___/|_| |_| |_|';
echo '<hr style="border-top: dotted 1px;" />';
echo '</pre>';
echo '<BODY BGCOLOR="#000"';
echo 'TEXT="#6fc3df"';
echo 'LINK="#e6ffff"';
echo 'VLINK="#e6ffff"';
echo 'ALINK="#e6ffff" ></BODY>';
echo '<font color="#6fc3df">Books</font>';
echo '';
echo '<p><font color="#6fc3df">>></font> <font color="#e6ffff">is long[400+ pages]</font>   </p>';
echo '<p><font color="#df7212">>></font> <font color="#e6ffff"> is short[400- pages]</font> </p>';
echo '<p><font color="red">>></font> <font color="#e6ffff">  is unavailable</font> </p>';
echo '';
echo '';
echo '<hr style="border-top: dotted 1px;" />';
echo '';
echo '';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="TAUNIXP.pdf">The Art of UNIX Programming</p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="vi^vim.pdf">Learning the vi and Vim Editors</p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="ghfg.pdf">Fingerprints of the Gods</p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="CLIW.pdf">The Linux® Command Line</p>';
echo '<p>';
echo '<font color="red">>></font><a href="duos.pdf">The Design of the UNIX® Operating System </p>';
echo '<p>';
echo '<font color="red">>></font><a href="nb200.pdf">Networking; A Beginners Guide 1st Edition </p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="ghnb.pdf">Networking; A Beginners Guide 5th Edition  </p>';
echo '<p>';
echo '<font color="#df7212">>></font><a href="taoi.pdf">The Art of Intrusiom</p>';
echo '<p>';
echo '<font color="#df7212">>></font><a href="taof.pdf">The Art of Decpetion  </p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="tarx.pdf">Hacking; The Art of Exploitation  </p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="mitcs2010.pdf">Mathematics for Computer Science 2010 | MIT  </p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="mitcs2017.pdf">Matmematics for Computer Science 2017 | MIT  </p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="nwfd.pdf">Networking For Dummies  </p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="ahsa.pdf">The Accidental SysAdmin Handbook   </p>';
echo '<p>';
echo '<font color="#6fc3df">>></font><a href="uians.pdf">UNIX in a Nutshell   </p>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<hr style="border-top: dotted 1px;" />';
echo '';
echo '<div id="Menu">';
echo '<a href="index.html" title="Home">Home</a><br />';
echo '<a href="projects.html" title="My projects">Projects</a><br />';
echo '<a href="matlab.html">Matlab</a><br />';
echo '<a href="misc.html">Misc</a><br />';
echo '<a href="books.html">Books</a><br />';
echo '<a href="site-design.html">Design-Notes</a><br />';
echo '<hr style="border-top: dotted 1px;" />';
echo '<!--<font color="orange">Links</font><br />';
echo '<a href="http://catb.org">ESRs Page</a><br />';
echo '<a href="https://forum.level1techs.com/">L1Ts Forum</a><br />';
echo '-->';
echo '</body>';
echo '</html>';
echo '';
?>
